name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install sbt (via Coursier)
        run: |
          curl -fLo cs https://git.io/coursier-cli-linux && chmod +x cs && ./cs setup --yes

      - name: Cache sbt
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: sbt-${{ runner.os }}-${{ hashFiles('**/build.sbt', '**/project/*.scala') }}
          restore-keys: sbt-${{ runner.os }}

      - name: Compile and test
        run: sbt test
